# Basic site info
title:                  "William Spies"
tagline:                "My Personal & Technical Blog"
description:            "Personal & Technical Blog of William Spies"
keywords:               "William Spies, blog, electronics, engineering, robotics"
og_locale:              "en_US"

# Site author info
author:
    name:               "William Spies"
    email:              admin@spieswl.com
    github_username:    spieswl

# Site settings & folders
url:                    null # https://www.spieswl.com for main url // # null for spieswl.github.io // # http://localhost:4000 for local testing
baseurl:                null # for master branch
enforce_ssl:            spieswl.com

assets:
    projects:           assets/images/projects
    posts:              assets/images/posts

# Projects info
collections:
    projects:
        output:         true
        permalink:      /projects/:year/:title

# Posts info
permalink:              /blog/:year/:title

# Build settings
source:                 ./
destination:            ./_site
markdown:               kramdown
highlighter:            rouge
timezone:               America/Denver
exclude:                ["README.md", "LICENSE.md"]

# Site configurations
compress_html:
    clippings:          all
    comments:           ["<!-- ", " -->"]
    endings:            all
    ignore:
        envs:           [local]
    blanklines:         false
    profile:            false
    startings:          [html, head, body]

sass:
    sass_dir:           assets/css/base
    style:              compressed # expanded

plugins_dir:
    - jekyll-sitemap
